### ISSUE TITLE
Subsubdirectories not recognized

### ISSUE THREAD

**Issue by ruefo** [syohex/emacs-dired-k#22]
I am using the melpa version 20150621.652 and sub-subdirectories are not recognized correctly as the screenshot shows.
![dired-k_issue](https://cloud.githubusercontent.com/assets/10230649/8845241/70b872d4-311d-11e5-9e9b-8d3e581d2815.png)

Don't mind that i adjusted the colors and used dired+.el. The issue is not connected.

**Comment by syohex** [comment]
I have changed at #23. Please check latest version.

**Comment by ruefo** [comment]
Sorry for late answer. Seems to be fixed, thanks.
