### ISSUE TITLE
`dired-k--root-directory' can fail

### ISSUE THREAD

**Issue by Alexander-Shukaev** [syohex/emacs-dired-k#24]
```
(defsubst dired-k--root-directory ()
  (expand-file-name (locate-dominating-file default-directory ".git/")))
```

Can you spot the problem?
> **HINT**  
What if there is no `.git/` subdirectory under `default-directory`?

Please, fix this.  Thank you!

**Comment by syohex** [comment]
dired-k checks whether current directory is git repository before calling dired-k--root-directory and if not,  dired-k does not call dired-k--root-directory.
(https://github.com/syohex/emacs-dired-k/blob/fcbbc4f0c94b3059bb384fea318e602481f3490d/dired-k.el#L325)

Please show me fail case and how to reproduce it if you get error.

**Comment by Alexander-Shukaev** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  dired-k--highlight()
  dired-k()
  run-hooks(dired-initial-position-hook)
  dired-initial-position("c:/Users/XXX/.emacs.d/init/")
  dired-internal-noselect("c:/Users/XXX/.emacs.d/init/" nil)
  dired-noselect("c:/Users/XXX/.emacs.d/init/" nil)
  dired("c:/Users/XXX/.emacs.d/init/")
  dired-jump(nil nil)
  funcall-interactively(dired-jump nil nil)
  call-interactively(dired-jump)
```

where `c:/Users/XXX/.emacs.d/` is, in fact, a *junction* (*symbolic link*) to another directory `x` which is part of Git repository (i.e. `x/../.git/` exists there).  Now, the point is that I **don't** ask you to implement support for such corner case (i.e. detect Git repository indirectly from symbolic links).  What I ask for is to just get rid of the error; that is `dired-k` should behave the same way as it does for regular directories which are not under Git repository at all — *skip Git processing*.

> **NOTE**  
If you are still interested in supporting this case, then `file-truename` will definitely come handy.

**Comment by syohex** [comment]
Please check latest version(#25)

**Comment by Alexander-Shukaev** [comment]
Perfect!  :+1:
