### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by justmytwospence** [syohex/emacs-dired-k#26]
The version control symbols are really squeezed in there, is it possible to put spaces around them?

**Comment by syohex** [comment]
How about #26 change ? I introduce padding variable `dired-k-padding`. Screenshots are following.

#### dired-k-padding==0

![dired-k-0](https://cloud.githubusercontent.com/assets/554281/10534411/360b8ade-7413-11e5-8a3f-9ea001804e60.png)

#### dired-k-padding==1

![dired-k-1](https://cloud.githubusercontent.com/assets/554281/10534414/3ab7426c-7413-11e5-9875-a2c83597878e.png)

#### dired-k-padding==2

![dired-k-2](https://cloud.githubusercontent.com/assets/554281/10534416/3f765432-7413-11e5-9cf0-f456b913a5dc.png)

**Comment by justmytwospence** [comment]
brilliant

**Comment by syohex** [comment]
merged
