### ISSUE TITLE
dired-k-human-readable has no effect

### ISSUE THREAD

**Issue by ninrod** [syohex/emacs-dired-k#36]
Hi, and thanks for this.

I'm trying to get the human readable behaviour, but to no avail using this code:

```elisp
(use-package dired-k :ensure t
    :init
      (setq dired-k-human-readable t)
      (setq dired-k-style 'git)
    :config
    (add-hook 'dired-initial-position-hook 'dired-k))
```

note: the `(setq dired-k-style 'git)` is working flawlessly. What am I doing wrong?

**Comment by syohex** [comment]
What do you except for it ? It does not mean outputting human readable output(sorry its name is confused). It is useful only for users who set `-h` or `--human-readable` option of `ls`(and load `ls-lisp` for using `ls` for `dired`)

**Comment by ninrod** [comment]
OH! all right, I though I'd get behaviour similar to what `k -h` does. 

no problem. thanks for explaining the behaviour.
