### ISSUE TITLE
dired-k and tramp: annoying prompts for passwords

### ISSUE THREAD

**Issue by timmli** [syohex/emacs-dired-k#39]
I'd like to use `dired-k` in all `dired` buffers, also in remote ones. However, using the proposed settings for this causes `tramp` to ask for my password every time a new remote `dired` buffer is created, which is, of course, a pain in the neck.  This is how my settings look like:

```
(use-package dired-k
	:ensure t
	:config
            (progn
		(add-hook 'dired-initial-position-hook 'dired-k)
		(add-hook 'dired-after-readin-hook #'dired-k-no-revert)))
```

**Comment by syohex** [comment]
Because dired-k executes commands on remote server on Tramp. dired-k cannot do anything about this. Please consider your ssh configuration. For example, use ssh-key instead of password etc.
