### ISSUE TITLE
Selecting deleted buffer

### ISSUE THREAD

**Issue by Alexander-Shukaev** [syohex/emacs-dired-k#40]
Occasionally, `dired-k--highlight-git-information` throws the following backtrace:

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  dired-k--highlight-git-information(#s(hash-table size 145 test equal rehash-size 1.5 rehash-threshold 0.8 data (...)) #<killed buffer>)
  #[514 "\306!\307=\205-
```

I believe, it would be safer to wrap the body of this function into the `(when (buffer-live-p buf) ...)` form.

**Comment by syohex** [comment]
Thanks for information. I have updated by #41.

**Comment by Alexander-Shukaev** [comment]
:+1:
